apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: kneonix/auth:latest
                  imagePullPolicy: Never
                  env:
                      # share environment
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: JWT_KEY
                        # specific environment
                      - name: PORT
                        value: "3000"

                      - name: MONGO_URL
                        value: "mongodb://auth-mongo-srv:27017"

---
apiVersion: v1
kind: Service
metadata:
    name: auth-clusterip-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
