apiVersion: apps/v1
kind: Deployment
metadata:
    name: expiration-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: expiration
    template:
        metadata:
            labels:
                app: expiration
        spec:
            containers:
                - name: expiration
                  image: kneonix/expiration:latest
                  imagePullPolicy: Never
                  env:
                      - name: KAFKA_BROKER_URI
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: KAFKA_BROKER_URI
                        # specific environment
                      - name: PORT
                        value: "3000"
                      - name: REDIS_HOST
                        value: "expiration-redis-srv"
                      - name: REDIS_PORT
                        value: "6379"
