apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payment
    template:
        metadata:
            labels:
                app: payment
        spec:
            containers:
                - name: payment
                  image: kneonix/payment:latest
                  imagePullPolicy: Never
                  env:
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: JWT_KEY
                      - name: KAFKA_BROKER_URI
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: KAFKA_BROKER_URI
                      - name: PORT
                        value: "3000"
                      - name: MONGO_URL
                        value: "mongodb://payment-mongo-srv:27017"

                      - name: ZARINPAL_API_URL
                        value: "https://sandbox.zarinpal.com"
                      - name: ZARINPAL_MERCHANT_ID
                        value: "e6a3f4c3-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                      - name: ZARINPAL_CALLBACK_URL
                        value: "https://ticketing.dev/payment/result"
---
apiVersion: v1
kind: Service
metadata:
    name: payment-clusterip-srv
spec:
    selector:
        app: payment
    ports:
        - name: payment
          protocol: TCP
          port: 3000
          targetPort: 3000
