apiVersion: apps/v1
kind: Deployment
metadata:
    name: ticket-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ticket
    template:
        metadata:
            labels:
                app: ticket
        spec:
            containers:
                - name: ticket
                  image: kneonix/ticket:latest
                  imagePullPolicy: Never
                  env:
                      # share environment
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: JWT_KEY
                      - name: KAFKA_BROKER_URI
                        valueFrom:
                            secretKeyRef:
                                name: shared-secret
                                key: KAFKA_BROKER_URI
                        # specific environment
                      - name: PORT
                        value: "3000"

                      - name: MONGO_URL
                        value: "mongodb://ticket-mongo-srv:27017"

---
apiVersion: v1
kind: Service
metadata:
    name: ticket-clusterip-srv
spec:
    selector:
        app: ticket
    ports:
        - name: ticket
          protocol: TCP
          port: 3000
          targetPort: 3000
